#!/bin/sh
#DdShurick GPL 03.02.14
[ "$(ls /dev/cdc-wdm*)" ] && exit
[ $1 ] || exit 1
Dx1=$1
[ -f /tmp/mdev ] && rm /tmp/mdev
/usr/sbin/modem-stats -c AT /dev/$Dx1 && echo $Dx1 >> /tmp/mdev
/bin/grep $Dx1 /tmp/mdev || exit 1
if [ $(/usr/bin/wc -l < /tmp/mdev) -nt 1 ]; then
ln -s $Dx1 /dev/modem
ln -s $Dx1 /dev/ttyUSB_utps_pcui
exec /lib/udev/wvdial.sh
else
 if [ $(/bin/find $(/usr/bin/dirname $(/usr/bin/realpath /sys/bus/usb-serial/devices/$Dx1)) -name ep_* | wc -w) = 3 ]; then
/bin/ln -s /dev/$Dx1 /dev/modem && exec /lib/udev/wvdial.sh 
 else
[ "$(/bin/grep $Dx1 /tmp/mdev)" ] && /bin/ln -s /dev/$Dx1 /dev/ttyUSB_utps_pcui
 fi
fi
