#!/bin/sh
#DdShurick GPL3 20.10.16
[ $1 ] || exit

chk_on () {
	/bin/echo "check $1" /tmp/network.log
	if [ "$(/bin/grep $(/bin/cat /sys/class/net/$1/address) /etc/network-wizard/network/interfaces.lck)" ]; then
		 /bin/grep "$(/bin/cat /sys/class/net/$1/address) on" /etc/network-wizard/network/interfaces.lck || exit
	else
		echo "$(/bin/cat /sys/class/net/$1/address) off" >> /etc/network-wizard/network/interfaces.lck
		exit
	fi
}

case $1 in
lo)
/sbin/ifconfig lo  127.0.0.1 up
/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo
;;
usb?)
chk_on $1
/bin/sleep 10
/usr/sbin/dhcpcd $1
/usr/bin/curl http://192.168.0.1/goform/goform_set_cmd_process?goformId=CONNECT_NETWORK
;;
#wwan?)
#chk_on $1
#/bin/sleep 1
#/usr/sbin/dhcpcd $1
#;;
wlan?|ra?)
chk_on $1
exec /usr/sbin/wlan.sh $1
;;
eth?)
chk_on $1
exec /usr/sbin/lan.sh $1
;;
esac
