#!/bin/sh
#DdShurick 25.08.18 GPL v2
if [ $(/usr/bin/id -u) = 0 ]; then DISPLAY="$(cat /tmp/dsp)"; else loginroot $0; exit; fi
. /usr/lib64/upNet/libupNet

if [ "$IFASE" ]; then
	IFACE=eth0
elif [ $(ls -1 /sys/class/net|grep ^e|wc -w) -gt 1 ]; then
#	IFACE=$(yad --list --column="Выберите интерфейс
#	для подключения PPPoE" $(ls -1 /sys/class/net|grep ^e)|tr -d \|)
	select_iface $(ls -1 /sys/class/net|grep ^e)
else
	IFACE=eth0
fi

ifup

CONFDIR="/etc/net/interfaces/"
HWADDR=$(/bin/cat /sys/class/net/$IFACE/address)
[ -f ${CONFDIR}${HWADDR}.pppoe.conf ] && . ${CONFDIR}${HWADDR}.pppoe.conf

export PPPOECONF="<window icon-name=\"network\" title=\" PPPoE\" resizable=\"false\"><vbox>
 <notebook labels=\"Авторизация| NIC и DNS | Прочее\">
  <vbox>
   <frame Имя соединения>
    <entry activates_default=\"true\">
     <default>\"$NAME\"</default>
     <variable>NAME</variable>
    </entry>
   </frame>
   <frame Логин>
    <entry activates_default=\"true\">
     <default>\"$LOGIN\"</default>
     <variable>LOGIN</variable>
    </entry>
   </frame>
   <frame Пароль>
    <entry activates_default=\"true\">
     <default>\"$PASSWD\"</default>
     <variable>PASSWD</variable>
    </entry>
   </frame>
  </vbox>
  <vbox>
   <text><label>Заполнять только при необходимости</label></text>
   <frame Static IP>
    <entry activates_default=\"true\">
     <default>*</default>
     <variable>IP</variable>
    </entry>
   </frame>
   <frame DNS1>
    <entry activates_default=\"true\">
     <default>\"$DNS1\"</default>
     <variable>DNS1</variable>
    </entry>
   </frame>
   <frame DNS2>
    <entry activates_default=\"true\">
     <default>\"$DNS2\"</default>
     <variable>DNS2</variable>
    </entry>
   </frame>
  </vbox>
  <vbox>
   <text><label>Заполнять только при необходимости</label></text>
   <frame Имя сервиса>
   	<entry><variable>SN</variable></entry>
   </frame>
   <frame Имя концентратора>
   	<entry><variable>AC</variable></entry>
   </frame>
  </vbox>
 </notebook>
 <hbox>
  <text><label>Если настроили, нажмите</label></text>
  <button ok></button>
 </hbox>
</vbox></window>
"
eval $(/usr/bin/gtkdialog -c --display "$(cat /tmp/dsp)" --program "PPPOECONF")

[ "$EXIT" = "abort" ] && exit 1
[ "$NAME" ] ||  MSG="Отсутствует: Имя_соединения"
[ "$LOGIN" ] || MSG="$MSG Логин"
[ "$PASSWD" ] || MSG="$MSG Пароль"
[ "$IP" = '*' ] || check_ip_err "$IP"
[ "$?" = 1 ] && MSG="$MSG Неверно: Static_IP"
[ "$DNS1" = "" ] || check_ip_err "$DNS1"
[ "$?" = 1 ] && MSG="$MSG Неверно: DNS1"
[ "$DNS2" = ""  ] || check_ip_err "$DNS2"
[ "$?" = 1 ] && MSG="$MSG Неверно: DNS2"
[ "$DNS1" = "" -a "$DNS2" = "" ] && DNS="usepeerdns"
[ "$SN" ] && DSN=" -S $SN"
[ "$AC" ] && DAC=" -C $AC"
if [ "$MSG" ]; then
	yad --text "$(echo $MSG | tr ' ' '\n')" --no-buttons --timeout=5 --borders=10
	exit
fi

IMG=search
msg "Поиск PPPoE..." &
pid=$!

if [ "$(/usr/sbin/pppoe-discovery -I ${IFACE}${DSN}${DAC})" ]; then
	/bin/echo "NAME=$NAME
LOGIN=$LOGIN
PASSWD=$PASSWD
IP=$IP" | /usr/bin/tee ${CONFDIR}${HWADDR}.pppoe.conf
	[ "$DNS" = "usepeerdns" ] && /bin/echo "DNS=$DNS" | /usr/bin/tee -a ${CONFDIR}${HWADDR}.pppoe.conf
	[ "$DNS1" ] && /bin/echo "DNS1=$DNS1" | /usr/bin/tee -a ${CONFDIR}${HWADDR}.pppoe.conf
	[ "$DNS2" ] && /bin/echo "DNS2=$DNS2" | /usr/bin/tee -a ${CONFDIR}${HWADDR}.pppoe.conf
	[ "$SN" ] && /bin/echo "SN=\"rp_pppoe_service $SN\"" | /usr/bin/tee -a ${CONFDIR}${HWADDR}.pppoe.conf
	[ "$AC" ] && /bin/echo "AC=\"rp_pppoe_ac $AC\"" | /usr/bin/tee -a ${CONFDIR}${HWADDR}.pppoe.conf
	kill $pid
	exec /usr/sbin/lan.sh $IFACE pppoeup
else
	IMG=connect_no
	msg_err "Нет доступа PPPoE"
fi
