#!/bin/sh
#DdShurick GPL v2 12.04.2019
[ "$1" ] || exit 0
[ "$(/usr/bin/id -u)" = "0" ] || exit 0
ST="$(/bin/grep $2 /etc/net/interfaces.lck | cut -f3 -d" ")"

if [ "$ST" ]; then
	[ "$ST" = "down" ] && exit 0
else
	/bin/echo "$@" | /usr/bin/tee -a /etc/net/interfaces.lck
	[ "$(/bin/echo $1 | /bin/egrep '^wl|^ra')" ] && exit 0 #не автостартовать wifi
fi

case $1 in
lo)
	/sbin/ifconfig lo 127.0.0.1 up
	/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo
;;
e[nt]*)
	/usr/sbin/lan.sh $1 &
;;
wl*|ra*)
	/usr/sbin/wlan.sh $1 &
;;
ww*|usb?)
	sleep 7
	/usr/sbin/lan.sh $1 &
;;
esac

until [ -s /tmp/dsp ]; do /bin/sleep 1; done;
[ "$(/bin/pidof netTun)" ] && exit 0
DISPLAY="$(cat /tmp/dsp)" /usr/bin/netTun &
