#!/bin/sh
#DdShurick GPL v2 
[ "$1" ] || exit 0
export PATH=/usr/bin:/usr/sbin:/bin:/sbin

ST="$(grep $2 /etc/net/interfaces.lck | cut -f3 -d" ")"

if [ "$ST" ]; then
	[ "$ST" = "down" ] && exit 0
elif [ "$1" = "lo" ]; then
	ifconfig lo 127.0.0.1 up
	route add -net 127.0.0.0 netmask 255.0.0.0 lo
	exit 0
else
	echo "$@" | tee -a /etc/net/interfaces.lck
	[ "$(echo $1 | grep ^e[nt])" ] || exit 0
fi

case $1 in
e[nt]*)
	lan.sh $1 &
;;
wl*)
	wlan.sh $1 &
;;
usb?|ww*)
	sleep 3
	lan.sh $1 &
;;
esac

until [ -s /tmp/dsp ]; do sleep 1; done;
[ "$(pidof netTun)" ] && exit 0
export DISPLAY="$(cat /tmp/dsp)" 
export $(grep LANG= /etc/profile)
netTun &
