#!/bin/sh
#wi-fi up. DdShurick 07.10.2018
if [ $(/usr/bin/id -u) = 0 ]; then DISPLAY="$(cat /tmp/dsp)"; else loginroot $0; exit; fi
[ "$(pidof wpa_supplicant)" ] && kill "$(pidof wpa_supplicant)"
[ "$(uname -m)" = "x86_64" -a -d /usr/lib64 ] && m=64
. /usr/lib${m}/upNet/libupNet
IMG="/usr/share/pixmaps/wireless"

ifdown () {
	[ $(pidof wpa_supplicant) ] && kill $(pidof wpa_supplicant)
	/sbin/ifconfig $IFACE down
	ADDR=$(grep $IFACE /etc/net/interfaces.lck | cut -f2 -d' ')
	sed -i "s/$IFACE $ADDR up/$IFACE $ADDR down/" /etc/net/interfaces.lck
	exit 1
}

IFACE=$(basename $(dirname /sys/class/net/*/phy80211)) 2>/dev/null
if [ "$IFACE" ]; then
	if [ "$(echo $IFACE | wc -w)" -gt 1 ]; then
		export Iface="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
		<text><label>Выберите интерфейс</label></text>
		<tree>
		 <variable>IFACE</variable>
		 $(echo "$IFACE" | sed 's/^/<item>/;s/$/<\/item>/')
		</tree>
		<button><label>Подключить</label></button>
		</vbox></window>"
		eval $(gtkdialog -c --program "Iface")
		[ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" ] && exit 1
	fi
else
	msg_err "$IFACE" "Нет wi-fi интерфейсов" &
	exit 1
fi

[ $(pidof wpa_supplicant) ] && kill $(pidof wpa_supplicant)
/sbin/ifconfig $IFACE up
sleep 2
iwlist $IFACE scan | egrep 'Address:|Channel:|Quality|Encryption key:|ESSID:' | tee /tmp/iwlist
export Window="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
  <text><label>Найдены сети Wi-Fi</label></text>
  <tree>
   <variable>MYESSID</variable>
   $(awk -F \: '/ESSID/ {print "<item>"$2"</item>"}' /tmp/iwlist)
  </tree>
  <button><label>Подключить</label></button>
 </vbox></window>"
eval $(gtkdialog -c --program "Window")

[ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" -o "$MYESSID" = "" ] && ifdown
[  "$EXIT" = "Подключить"  ] || ifdown

KEY=$(grep $MYESSID -B 1 /tmp/iwlist | awk '/Encryption/ {print $2}')
if [ "$KEY" = "key:on" ]; then
	export Passw="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
  <text><label>Введите пароль для $MYESSID</label></text>
  <entry>
   <visible>password</visible>
   <variable>MYPASSWD</variable>
  </entry>
  <button><label>Подключить</label></button>
</vbox></window>"
	eval $(gtkdialog -c --program "Passw") 
	[ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" ] && ifdown
	[ "$MYPASSWD" ] || ifdown
	[  "$EXIT" = "Подключить"  ] || ifdown
	wpa_passphrase "$MYESSID" "$MYPASSWD" | grep -v '#psk' | tee /tmp/wpa.conf
	if /usr/sbin/wpa_supplicant -B -D nl80211 -i $IFACE -c /tmp/wpa.conf; then 2>&1 | tee -a /var/log/${IFACE}.log
		
		dhcpc $(/sbin/udhcpc -i $IFACE -n 2>/dev/null) 
		if [ $? = 0 ]; then
			export Addr="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\">
	<frame Сеть $MYESSID Ok>
	<vbox>
		<text><label>Сохранить настройки ${MYESSID}?</label></text>
		<pixmap><height>64</height>
			<input file>$IMG</input>
		</pixmap>
		<hbox><button yes>
			<action function=\"exit\">Сохранить</action>
		</button>
		<button no></button></hbox>
	</vbox>
	</frame>
</window>"
			eval $(gtkdialog -c --program "Addr") 
			[ "$EXIT" = "abort" ] && ifdown
			MYADDR=$(grep -B 5 "$MYESSID" /tmp/iwlist | awk '/Address/ {print $5}')
			cp /tmp/wpa.conf /etc/net/wpa_profiles/${MYADDR}.wpa.conf
		else
			tunstatic $IFACE
		fi
	else
		ifdown
	fi
elif [ "$KEY" = "key:off" ]; then
	iwconfig $IFACE essid "$MYESSID" key off
	dhcpc $(/sbin/udhcpc -i $IFACE -n 2>/dev/null) 
fi
