#!/bin/sh
#wi-fi up. DdShurick GPL v2

if [ $(id -u) != 0 ]; then loginroot $0; exit 0; fi

. /usr/lib64/upNet/libupNet
WPADIR="/etc/net/wpa_profiles/"
IMG="wireless_"

IFACE=$(basename $(dirname /sys/class/net/*/phy80211)) 2>/dev/null
if [ "$IFACE" ]; then
	if [ "$(echo $IFACE | wc -w)" -gt 1 ]; then
		export Iface="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
		<text><label>Выберите интерфейс</label></text>
		<tree>
		 <variable>IFACE</variable>
		 $(echo "$IFACE" | sed 's/^/<item>/;s/$/<\/item>/')
		</tree>
		<button><label>Подключить</label></button>
		</vbox></window>"
		eval $(gtkdialog -c --program "Iface")
		[ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" ] && exit 1
	fi
else
	export Iface="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
	<text><label>Нет wi-fi интерфейсов</label></text>
	<button><label>Выйти</label></button>
	</vbox></window>"
	eval $(gtkdialog -c --program "Iface")
	exit 1
fi
#[ $(pidof dhcpcd) ] && dhcpcd -k $IFACE
[ $(pidof wpa_supplicant) ] && kill $(pidof wpa_supplicant)
ifup

[ "$1" = "noscan" ] || iwlist $IFACE scan | egrep 'Address:|Channel:|Quality|Encryption key:|ESSID:' | tee /tmp/iwlist
export Window="<window title=\"Wi-Fi\"><vbox>
  <text><label>Найдены сети Wi-Fi</label></text>
  <list>
   <variable>MYESSID</variable>
   $(awk -F \: '/ESSID/ {print "<item>"$2"</item>"}' /tmp/iwlist)
  </list>
  <button><label>Подключить</label></button>
 </vbox></window>"
eval $(gtkdialog -c --program "Window")

[ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" -o "$MYESSID" = "" ] && ifdown
[  "$EXIT" = "Подключить"  ]|| ifdown

WLNADDR=$(grep -B 4 $MYESSID /tmp/iwlist | awk '/Address:/ {print $5}')
KEY=$(grep -B 1 $MYESSID /tmp/iwlist | awk '/Encryption/ {print $2}')

if [ "$KEY" = "key:on" ]; then
	if [ -f ${WPADIR}${WLNADDR}.wpa.conf ]; then
	 cp ${WPADIR}${WLNADDR}.wpa.conf /tmp/wpa.conf
	 noexit=no
	else
	 export Passw="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
  <text><label>Введите пароль для $MYESSID</label></text>
  <entry>
   <visible>password</visible>
   <variable>MYPASSWD</variable>
  </entry>
  <button><label>Подключить</label></button>
</vbox></window>"
	 eval $(gtkdialog -c --program "Passw") 
	 [ "$EXIT" = "Cancel" -o  "$EXIT" = "abort" ] && exit 1
	 [ "$MYPASSWD" ] || exit 1
	 [  "$EXIT" = "Подключить"  ] || exit 1
	 wpa_passphrase "$MYESSID" "$MYPASSWD" | grep -v '#psk' | tee /tmp/wpa.conf
	fi
	if wpa_supplicant -B -D nl80211 -i $IFACE -c /tmp/wpa.conf; then 2>&1 | tee -a /var/log/${IFACE}.log
		dhcpc
		
		if [ "$?" = 0 ]; then
			[ "$noexit" = "no" ] && exit 0
			export Addr="<window icon-name=\"network\" title=\"Wi-Fi\" resizable=\"false\"><vbox>
  <frame Сеть $MYESSID Ok>
  <text><label>Сохранить ${MYESSID}?</label></text>
	<hbox>
		<button yes></button>
		<button no></button>
	</hbox>
</frame></vbox></window>"
			eval $(gtkdialog -c --program "Addr") 
			[ "$EXIT" = "No" -o  "$EXIT" = "abort" ] && exit
			[ "$EXIT" = "Yes"  ] || exit
			MYADDR=$(grep -B 5 "$MYESSID" /tmp/iwlist | awk '/Address/ {print $5}')
			cp /tmp/wpa.conf /etc/net/wpa_profiles/${MYADDR}.wpa.conf
		else
			tunstatic $IFACE
		fi
	else
		ifdown
	fi
elif [ "$KEY" = "key:off" ]; then
	iwconfig $IFACE essid "$MYESSID" key off
	dhcpc
fi
